version: "3.5"
services:

  postgresql:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: flask
      POSTGRES_DB: flask
      POSTGRES_USER: flask
    volumes:
      - /opt/docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8099:8080